services:
  surrealdb:
    image: surrealdb/surrealdb:latest-dev
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - surrealdb_data:/data
    command: ['start', '--user', 'root', '--pass', 'root', 'rocksdb:/data/mydatabase.db']

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--save', '60', '1', '--loglevel', 'warning']

volumes:
  redis_data:
    driver: local
  surrealdb_data:
    driver: local
